<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<script type="text/javascript">
		function* go(){
			try{
				yield 3;
			}catch(e){
				console.log(e)  //  throw 方法 抛出的错误
			}
			throw new Error('throw 命令 抛出的错误');
			yield 4;
		}
		var foo = go();
		var m = foo.next();
		console.log(m)  // {value: 3, done: false}
		try{ 
			var n = foo.throw('throw 方法 抛出的错误');  	
			console.log(n)	//  不会执行，因为throw抛出了错误，将进入catch语句
		}catch(e){
			console.log(e)	// throw 命令 抛出的错误
		}						
		//  {value: 3, done: false}
		//  {value: 3, done: false}
		//  throw 命令 抛出的错误
		</script>
	</body>
</html>